%% AOC MASTER Matrix Nback
clear
clc
close all

%% Load data
% Demographics from methlab_vp
demog_data_nback = readtable('/Volumes/g_psyplafor_methlab$/VP/OCC/AOC/AOC_VPs.xlsx');
demog_data_nback = demog_data_nback(:, {'ID', 'Gender', 'Alter', 'H_ndigkeit', 'OcularDominance'});
demog_data_nback = table2struct(demog_data_nback(1:120, :));

% Behavioral
load('/Volumes/g_psyplafor_methlab$/Students/Arne/AOC/data/features/behavioral_matrix_nback.mat');

% EEG
load('/Volumes/g_psyplafor_methlab$/Students/Arne/AOC/data/features/eeg_matrix_nback.mat');

% Gaze
load('/Volumes/g_psyplafor_methlab$/Students/Arne/AOC/data/features/gaze_matrix_nback.mat');

%% Merge structures
demoIDs = [demog_data_nback.ID];
for i = 1:numel(behav_data_nback)
    idx = find(demoIDs == behav_data_nback(i).ID, 1);
    behav_data_nback(i).Gender           = demog_data_nback(idx).Gender;
    behav_data_nback(i).Alter            = demog_data_nback(idx).Alter;
    behav_data_nback(i).H_ndigkeit       = demog_data_nback(idx).H_ndigkeit;
    behav_data_nback(i).OcularDominance  = demog_data_nback(idx).OcularDominance;
end

% Merge all
merged_data_nback = struct( ...
    'ID', {behav_data_nback.ID}, ...
    'Gender', {behav_data_nback.Gender}, ...
    'Age', {behav_data_nback.Alter}, ...
    'Handedness', {behav_data_nback.H_ndigkeit}, ...
    'OcularDominance', {behav_data_nback.OcularDominance}, ...
    'Condition', {behav_data_nback.Condition}, ...
    'Accuracy', {behav_data_nback.Accuracy}, ...
    'ReactionTime', {behav_data_nback.ReactionTime}, ...
    'GazeDeviation', {gaze_data_nback.GazeDeviation}, ...
    'GazeStdX', {gaze_data_nback.GazeStdX}, ...
    'GazeStdY', {gaze_data_nback.GazeStdY}, ...
    'PupilSize', {gaze_data_nback.PupilSize}, ...
    'MSRate', {gaze_data_nback.MSRate}, ...
    'Blinks', {gaze_data_nback.Blinks}, ...
    'Fixations', {gaze_data_nback.Fixations}, ...
    'Saccades', {gaze_data_nback.Saccades}, ...
    'ScanPathLength', {gaze_data_nback.ScanPathLength}, ...
    'AlphaPower', {eeg_data_nback.AlphaPower}, ...
    'IAF', {eeg_data_nback.IAF},...
    'Lateralization', {eeg_data_nback.Lateralization});

%% Save as .mat
save /Volumes/g_psyplafor_methlab$/Students/Arne/AOC/data/features/merged_data_nback.mat merged_data_nback

%% Save as .csv
merged_table = struct2table(merged_data_nback);
csv_filename = '/Volumes/g_psyplafor_methlab$/Students/Arne/AOC/data/features/merged_data_nback.csv';
writetable(merged_table, csv_filename);