%% AOC MASTER Matrix Sternberg

%% Setup
clear
clc
close all
path = '/Volumes/methlab/Students/Arne/AOC/data/';
dirs = dir(path);
folders = dirs([dirs.isdir] & ~ismember({dirs.name}, {'.', '..'}));
subjects = {folders.name};

%% Load data
load('/Volumes/methlab/Students/Arne/AOC/data/features/behavioral_matrix_sternberg.mat');
load('/Volumes/methlab/Students/Arne/AOC/data/features/eeg_matrix_sternberg.mat');
load('/Volumes/methlab/Students/Arne/AOC/data/features/gaze_matrix_sternberg.mat');

%% Merge structures
merged_data_sternberg = struct('ID', {behav_data_sternberg.ID}, ...
    'Condition', {behav_data_sternberg.Condition}, ...
    'Accuracy', {behav_data_sternberg.Accuracy}, ...
    'ReactionTime', {behav_data_sternberg.ReactionTime}, ...
    'GazeDeviation', {gaze_data_sternberg.GazeDeviation}, ...
    'GazeStdX', {gaze_data_sternberg.GazeStdX}, ...
    'GazeStdY', {gaze_data_sternberg.GazeStdY}, ...
    'PupilSize', {gaze_data_sternberg.PupilSize}, ...
    'MSRate', {gaze_data_sternberg.MSRate}, ...
    'Blinks', {gaze_data_sternberg.Blinks}, ...
    'Fixations', {gaze_data_sternberg.Fixations}, ...
    'Saccades', {gaze_data_sternberg.Saccades}, ...
    'AlphaPower', {eeg_data_sternberg.AlphaPower}, ...
    'IAF', {eeg_data_sternberg.IAF},...
    'Lateralization', {eeg_data_sternberg.Lateralization});

%% Save as .mat
save /Volumes/methlab/Students/Arne/AOC/data/features/merged_data_sternberg.mat merged_data_sternberg

%% Save as .csv
merged_table = struct2table(merged_data_sternberg);
csv_filename = '/Volumes/methlab/Students/Arne/AOC/data/features/merged_data_sternberg.csv';
writetable(merged_table, csv_filename);