%% AOC MASTER Matrix Nback

%% Setup
clear
clc
close all
path = '/Volumes/methlab/Students/Arne/AOC/data/';
dirs = dir(path);
folders = dirs([dirs.isdir] & ~ismember({dirs.name}, {'.', '..'}));
subjects = {folders.name};

%% Load data
load('/Volumes/methlab/Students/Arne/AOC/data/features/behavioral_matrix_nback.mat');
load('/Volumes/methlab/Students/Arne/AOC/data/features/eeg_matrix_nback.mat');
load('/Volumes/methlab/Students/Arne/AOC/data/features/gaze_matrix_nback.mat');

%% Merge structures
merged_data_nback = struct('ID', {behav_data_nback.ID}, ...
    'Condition', {behav_data_nback.Condition}, ...
    'Accuracy', {behav_data_nback.Accuracy}, ...
    'ReactionTime', {behav_data_nback.ReactionTime}, ...
    'GazeDeviation', {gaze_data_nback.GazeDeviation}, ...
    'GazeStdX', {gaze_data_nback.GazeStdX}, ...
    'GazeStdY', {gaze_data_nback.GazeStdY}, ...
    'PupilSize', {gaze_data_nback.PupilSize}, ...
    'MSRate', {gaze_data_nback.MSRate}, ...
    'Blinks', {gaze_data_nback.Blinks}, ...
    'Fixations', {gaze_data_nback.Fixations}, ...
    'Saccades', {gaze_data_nback.Saccades}, ...
    'AlphaPower', {eeg_data_nback.AlphaPower}, ...
    'IAF', {eeg_data_nback.IAF});

%% Save as .mat
save /Volumes/methlab/Students/Arne/AOC/data/features/merged_data_nback.mat merged_data_nback

%% Save as .csv
merged_table = struct2table(merged_data_nback);
csv_filename = '/Volumes/methlab/Students/Arne/AOC/data/features/merged_data_nback.csv';
writetable(merged_table, csv_filename);